/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.frame;

import javax.swing.ImageIcon;
import br.edu.model.Candidato;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import br.edu.frame.TelaFinal;
import java.util.Arrays;
import br.edu.model.Utilitarios;



/**
 *
 * @author r1skin
 */
public class TelaUrna extends javax.swing.JFrame {

    /**
     * Creates new form TelaUrna
     */
    
    String primeiro, segundo, terceiro;
    String senha;
    String senhaurna = "ordemeprogresso";
    int somaVotosValidos = 0;
    Timer t;
    Candidato[] candidatos;
    int votosBrancos = 0;
    int votosNulos = 0;
    public TelaUrna() {
        initComponents();
        setLocationRelativeTo(null);
        Utilitarios u = new Utilitarios();
        u.InserirIcone(this);
        initCandidatos();
        esconderFotos();
        panelFim.setVisible(false);
    }
    public void votoBranco() {
        panelNum1.setVisible(false);
        panelNum2.setVisible(false);

    }
    
    
    
    public void telaFinal() {
        for (Candidato candidato : candidatos) {
            somaVotosValidos =somaVotosValidos+ candidato.votos;
        }
        if(senha.equals(senhaurna)&somaVotosValidos>0){
            this.dispose();
            new TelaFinal(candidatos, votosBrancos, votosNulos).setVisible(true);
            
//             TelaUrna.setVisible(false);
        } else if (senha.equals(senhaurna)&somaVotosValidos<1) {
            JOptionPane.showMessageDialog(
        null, "Sem votos válidos.", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(
        null, "Senha incorreta.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    

    public void mostrarFotos(){
        lblFotoPrefeito.setVisible(true);
        panelPrefeito.setVisible(true);
        lblFotoVice.setVisible(true);
        panelVice.setVisible(true);
        lblViceCandidato.setVisible(true);
        lblPartidoCandidato.setVisible(true);
        lblNomeCandidato.setVisible(true);
        lblNumeroCandidato.setVisible(true);
        lblNomeC.setVisible(true);
        lblNomeP.setVisible(true);
        lblNomeV.setVisible(true);
    }
    
    public void esconderFotos(){
        lblFotoPrefeito.setVisible(false);
        panelPrefeito.setVisible(false);
        lblFotoVice.setVisible(false);
        panelVice.setVisible(false);
        lblViceCandidato.setVisible(false);
        lblPartidoCandidato.setVisible(false);
        lblNomeCandidato.setVisible(false);
        lblNumeroCandidato.setVisible(false);
        lblNomeC.setVisible(false);
        lblNomeP.setVisible(false);
        lblNomeV.setVisible(false);
        lblNumeroErrado.setText("");
        lblVotoNulo.setText("");
        lblNumeroErrado.setVisible(true);
        lblVotoNulo.setVisible(true);
        lblVotoBranco.setText("");

    }
 
    public void initCandidatos(){
        
        candidatos = new Candidato[9];
        candidatos[0] = new Candidato("André Fernandes", "PL", "Alcyvania Pinheiro", "22","/br/edu/images/fotoAndreFernandes.jpg", "/br/edu/images/fotoAlcyvaniaPinheiro.jpg");
        candidatos[1] = new Candidato("Wagner Sousa", "União Brasil", "Edilene Santos", "44","/br/edu/images/fotoCapitaoWagner.jpg" ,"/br/edu/images/fotoEdileneSantos.jpg");
        candidatos[2] = new Candidato("José Sarto", "PDT", "Elcio Batista", "12", "/br/edu/images/fotoSarto.jpg", "/br/edu/images/fotoElcioBatista.jpg");
        candidatos[3] = new Candidato("Evandro Leitão", "PT", "Gabriella Aguiar", "13", "/br/edu/images/fotoEvandroLeitao.jpg", "/br/edu/images/fotoGabriellaAguiar.jpg");
        candidatos[4] = new Candidato("George Lima", "Solidariedade", "Rachel Girão", "77", "/br/edu/images/fotoGeorgeLima.jpeg", "/br/edu/images/fotoRachelGirao.jpeg");
        candidatos[5] = new Candidato("Técio Nunes", "PSol", "Cindy Carvalho", "50","/br/edu/images/fotoTecioNunes.jpg", "/br/edu/images/fotoCindyCarvalho.jpg");
        candidatos[6] = new Candidato("Zé Batista", "PSTU", "Maria de Lourdes", "16", "/br/edu/images/fotoZeBatista.jpg", "/br/edu/images/fotoMalu.jpg");
        candidatos[7] = new Candidato("Eduardo Girão", "Novo", "Silvana Bezerra", "30", "/br/edu/images/fotoEduardoGirao.jpeg", "/br/edu/images/fotoSilvanaBezerra.jpeg");
        candidatos[8] = new Candidato("Chico Malta", "PCB", "Roberto Cabeludo", "21", "/br/edu/images/fotoChicoMalta.jpg", "/br/edu/images/fotoRobertoCabeludo.jpg");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void checaLabel1Vazia(String b){
        if(!panelFim.isVisible()){
            if(lblNum1.getText().equals("")){
            lblNum1.setText(b);
            } else if(!lblNum1.getText().equals("") &lblNum2.getText().equals("")) {
            lblNum2.setText(b);
            String numeroP = lblNum1.getText() + lblNum2.getText();
        
                for (Candidato candidato : candidatos) {
                    if ((candidato.numero).equals(numeroP)) {
                    mostrarFotos();
                
                    lblFotoPrefeito.setIcon(new javax.swing.ImageIcon(getClass().getResource(candidato.fotoprefeito)));
                    lblFotoVice.setIcon(new javax.swing.ImageIcon(getClass().getResource(candidato.fotovice)));
                    lblNomeC.setText(candidato.nome);
                    lblNomeP.setText(candidato.partido);
                    lblNomeV.setText(candidato.vice);
                    lblPrefeito.setText("PREFEITO");
                    lblNumeroErrado.setVisible(false);
                    lblVotoNulo.setVisible(false);
                    } else{
                        if(!lblNum1.equals("")&!lblNum2.equals("")){
                            lblNumeroErrado.setText("NÚMERO ERRADO");
                            lblVotoNulo.setText("VOTO NULO");
                        }
                    }
                }      
            }
        } 
        
        
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFim = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFotoPrefeito = new javax.swing.JLabel();
        panelPrefeito = new javax.swing.JPanel();
        lblSepPrefeito = new javax.swing.JLabel();
        lblFotoVice = new javax.swing.JLabel();
        panelVice = new javax.swing.JPanel();
        lblSepVice = new javax.swing.JLabel();
        lblPrefeito = new javax.swing.JLabel();
        lblViceCandidato = new javax.swing.JLabel();
        lblPartidoCandidato = new javax.swing.JLabel();
        lblNumeroCandidato = new javax.swing.JLabel();
        lblNomeCandidato = new javax.swing.JLabel();
        lblNomeC = new javax.swing.JLabel();
        lblNomeP = new javax.swing.JLabel();
        lblNomeV = new javax.swing.JLabel();
        lblNumeroErrado = new javax.swing.JLabel();
        lblVotoNulo = new javax.swing.JLabel();
        lblVotoBranco = new javax.swing.JLabel();
        panelNum2 = new javax.swing.JPanel();
        lblNum2 = new javax.swing.JLabel();
        panelNum1 = new javax.swing.JPanel();
        lblNum1 = new javax.swing.JLabel();
        lblConfirma = new javax.swing.JLabel();
        lblCorrige = new javax.swing.JLabel();
        panelSeparador = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnBranco = new javax.swing.JButton();
        btnConfirma = new javax.swing.JButton();
        btnCorrige = new javax.swing.JButton();
        figmaUrna = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFim.setBackground(new java.awt.Color(255, 255, 255));
        panelFim.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 108)); // NOI18N
        jLabel1.setText("FIM!");
        panelFim.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("VOTO COMPUTADO");
        panelFim.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, -1));

        getContentPane().add(panelFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 80, 525, 440));

        lblFotoPrefeito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/images/fotoAndreFernandes.jpg"))); // NOI18N
        getContentPane().add(lblFotoPrefeito, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, 160));

        panelPrefeito.setBackground(new java.awt.Color(255, 255, 255));
        panelPrefeito.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        lblSepPrefeito.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSepPrefeito.setText("Prefeito");

        javax.swing.GroupLayout panelPrefeitoLayout = new javax.swing.GroupLayout(panelPrefeito);
        panelPrefeito.setLayout(panelPrefeitoLayout);
        panelPrefeitoLayout.setHorizontalGroup(
            panelPrefeitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrefeitoLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblSepPrefeito)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        panelPrefeitoLayout.setVerticalGroup(
            panelPrefeitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrefeitoLayout.createSequentialGroup()
                .addComponent(lblSepPrefeito)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(panelPrefeito, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 190, 30));

        lblFotoVice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/images/fotoEdileneSantos.jpg"))); // NOI18N
        getContentPane().add(lblFotoVice, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, 160));

        panelVice.setBackground(new java.awt.Color(255, 255, 255));
        panelVice.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        lblSepVice.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblSepVice.setText("Vice-Prefeito");

        javax.swing.GroupLayout panelViceLayout = new javax.swing.GroupLayout(panelVice);
        panelVice.setLayout(panelViceLayout);
        panelViceLayout.setHorizontalGroup(
            panelViceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViceLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblSepVice)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelViceLayout.setVerticalGroup(
            panelViceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViceLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblSepVice))
        );

        getContentPane().add(panelVice, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 160, 30));

        lblPrefeito.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblPrefeito.setText("PREFEITO(A)");
        getContentPane().add(lblPrefeito, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 200, -1));

        lblViceCandidato.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblViceCandidato.setText("Vice:");
        getContentPane().add(lblViceCandidato, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        lblPartidoCandidato.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblPartidoCandidato.setText("Partido:");
        getContentPane().add(lblPartidoCandidato, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        lblNumeroCandidato.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblNumeroCandidato.setText("Número:");
        getContentPane().add(lblNumeroCandidato, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        lblNomeCandidato.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblNomeCandidato.setText("Nome:");
        getContentPane().add(lblNomeCandidato, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        lblNomeC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(lblNomeC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 210, 40));

        lblNomeP.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(lblNomeP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 160, 40));

        lblNomeV.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(lblNomeV, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 210, 40));

        lblNumeroErrado.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        getContentPane().add(lblNumeroErrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 320, 80));

        lblVotoNulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        getContentPane().add(lblVotoNulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 220, 50));
        lblVotoNulo.getAccessibleContext().setAccessibleName("lblVotoNulo");

        lblVotoBranco.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        getContentPane().add(lblVotoBranco, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 440, 70));

        panelNum2.setBackground(new java.awt.Color(255, 255, 255));
        panelNum2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        lblNum2.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        lblNum2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelNum2Layout = new javax.swing.GroupLayout(panelNum2);
        panelNum2.setLayout(panelNum2Layout);
        panelNum2Layout.setHorizontalGroup(
            panelNum2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNum2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );
        panelNum2Layout.setVerticalGroup(
            panelNum2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNum2, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        getContentPane().add(panelNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 60, 80));

        panelNum1.setBackground(new java.awt.Color(255, 255, 255));
        panelNum1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        lblNum1.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        lblNum1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelNum1Layout = new javax.swing.GroupLayout(panelNum1);
        panelNum1.setLayout(panelNum1Layout);
        panelNum1Layout.setHorizontalGroup(
            panelNum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNum1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );
        panelNum1Layout.setVerticalGroup(
            panelNum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNum1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        getContentPane().add(panelNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 60, 80));

        lblConfirma.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblConfirma.setText("VERDE para confirmar este voto ");
        getContentPane().add(lblConfirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        lblCorrige.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCorrige.setText("VERMELHO para REINICIAR este voto");
        getContentPane().add(lblCorrige, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, 40));

        panelSeparador.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(panelSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 434, 520, 4));

        btn1.setContentAreaFilled(false);
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 70, 50));

        btn2.setContentAreaFilled(false);
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 70, 50));

        btn3.setContentAreaFilled(false);
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, 70, 50));

        btn4.setContentAreaFilled(false);
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 70, 60));

        btn5.setContentAreaFilled(false);
        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, 70, 60));

        btn6.setContentAreaFilled(false);
        btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 220, 70, 60));

        btn7.setContentAreaFilled(false);
        btn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 70, 50));

        btn8.setContentAreaFilled(false);
        btn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, 70, 50));

        btn9.setContentAreaFilled(false);
        btn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 300, 70, 50));

        btn0.setContentAreaFilled(false);
        btn0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, 70, 60));

        btnBranco.setContentAreaFilled(false);
        btnBranco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBranco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrancoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBranco, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, 100, 50));

        btnConfirma.setContentAreaFilled(false);
        btnConfirma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmaActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, 100, 70));

        btnCorrige.setContentAreaFilled(false);
        btnCorrige.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCorrige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorrigeActionPerformed(evt);
            }
        });
        getContentPane().add(btnCorrige, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 90, 50));

        figmaUrna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/images/urnaPoo.jpg"))); // NOI18N
        figmaUrna.setFocusable(false);
        figmaUrna.setName(""); // NOI18N
        figmaUrna.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(figmaUrna, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        figmaUrna.getAccessibleContext().setAccessibleDescription("");

        jMenuBar1.setBorder(null);

        jMenu1.setBorder(null);
        jMenu1.setText("Mais");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Encerrar Votação");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        checaLabel1Vazia("1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        checaLabel1Vazia("2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        checaLabel1Vazia("3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        checaLabel1Vazia("4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        checaLabel1Vazia("5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        checaLabel1Vazia("6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        checaLabel1Vazia("7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        checaLabel1Vazia("8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        checaLabel1Vazia("9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnBrancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrancoActionPerformed
        esconderFotos();
        lblNum1.setText("B");
        lblNum2.setText("B");
        lblVotoBranco.setText("VOTO EM BRANCO");
        votoBranco();
    }//GEN-LAST:event_btnBrancoActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        checaLabel1Vazia("0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmaActionPerformed
        String numeroP = lblNum1.getText() + lblNum2.getText();
        if(!lblNum1.getText().equals("") & !lblNum2.getText().equals("")){
            for (Candidato candidato : candidatos) {
                if (candidato.numero.equals(numeroP)) {
                    candidato.votos = candidato.votos +1;
                    break;
                } 
            }
            if (lblVotoBranco.getText().equals("VOTO EM BRANCO")){
            votosBrancos = votosBrancos +1;
           } else if(lblVotoNulo.isVisible()& lblVotoNulo.getText().equals("VOTO NULO")&lblNumeroErrado.getText().equals("NÚMERO ERRADO")){
            votosNulos = votosNulos +1;
            }
            esconderFotos();
            lblNum1.setText("");
            lblNum2.setText("");
            lblPrefeito.setText("PREFEITO(A)");
            panelNum1.setVisible(true);
            panelNum2.setVisible(true);
            panelFim.setVisible(true);
            
            
            t=new Timer(3000, new ActionListener(){
            @Override
                public void actionPerformed(ActionEvent e) {
                    panelFim.setVisible(false);
                    System.out.println("Tela fim desaparece.");
                }
            });
            t.start();
        }
        t.setRepeats(false);
    }//GEN-LAST:event_btnConfirmaActionPerformed

    private void btnCorrigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorrigeActionPerformed
        esconderFotos();
        lblNum1.setText("");
        lblNum2.setText("");
        lblPrefeito.setText("PREFEITO(A)");
        panelNum1.setVisible(true);
        panelNum2.setVisible(true);
    }//GEN-LAST:event_btnCorrigeActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        senha = JOptionPane.showInputDialog(null,"Insira a senha:", "Sistema", JOptionPane.DEFAULT_OPTION);
        telaFinal();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUrna().setVisible(true);
            }
        });
        
//        Timer timer = new Timer();
//        TimerTask task;
//        task = new TimerTask(){
//            @Override
//            public void run() {
//                panelFim.setVisible(false);
//            }
//        };
    }

  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBranco;
    private javax.swing.JButton btnConfirma;
    private javax.swing.JButton btnCorrige;
    private javax.swing.JLabel figmaUrna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblConfirma;
    private javax.swing.JLabel lblCorrige;
    private javax.swing.JLabel lblFotoPrefeito;
    private javax.swing.JLabel lblFotoVice;
    private javax.swing.JLabel lblNomeC;
    private javax.swing.JLabel lblNomeCandidato;
    private javax.swing.JLabel lblNomeP;
    private javax.swing.JLabel lblNomeV;
    private javax.swing.JLabel lblNum1;
    private javax.swing.JLabel lblNum2;
    private javax.swing.JLabel lblNumeroCandidato;
    private javax.swing.JLabel lblNumeroErrado;
    private javax.swing.JLabel lblPartidoCandidato;
    private javax.swing.JLabel lblPrefeito;
    private javax.swing.JLabel lblSepPrefeito;
    private javax.swing.JLabel lblSepVice;
    private javax.swing.JLabel lblViceCandidato;
    private javax.swing.JLabel lblVotoBranco;
    private javax.swing.JLabel lblVotoNulo;
    private static javax.swing.JPanel panelFim;
    private javax.swing.JPanel panelNum1;
    private javax.swing.JPanel panelNum2;
    private javax.swing.JPanel panelPrefeito;
    private javax.swing.JPanel panelSeparador;
    private javax.swing.JPanel panelVice;
    // End of variables declaration//GEN-END:variables
}
