/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.frame;

/**
 *
 * @author r1skin
 */
public class TelaUrna extends javax.swing.JFrame {

    /**
     * Creates new form TelaUrna
     */
    public TelaUrna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFotoPrefeito = new javax.swing.JLabel();
        panelPrefeito = new javax.swing.JPanel();
        lblSepPrefeito = new javax.swing.JLabel();
        lblFotoVice = new javax.swing.JLabel();
        panelVice = new javax.swing.JPanel();
        lblSepVice = new javax.swing.JLabel();
        lblPrefeito = new javax.swing.JLabel();
        lblViceCandidato = new javax.swing.JLabel();
        lblPartidoCandidato = new javax.swing.JLabel();
        lblNumeroCandidato = new javax.swing.JLabel();
        lblNomeCandidato = new javax.swing.JLabel();
        panelNum2 = new javax.swing.JPanel();
        lblNum2 = new javax.swing.JLabel();
        panelNum1 = new javax.swing.JPanel();
        lblNum1 = new javax.swing.JLabel();
        lblConfirma = new javax.swing.JLabel();
        lblCorrige = new javax.swing.JLabel();
        panelSeparador = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnBranco = new javax.swing.JButton();
        btnConfirma = new javax.swing.JButton();
        btnCorrige = new javax.swing.JButton();
        figmaUrna = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFotoPrefeito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/images/fotoCapitaoWagner.jpg"))); // NOI18N
        getContentPane().add(lblFotoPrefeito, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, 160));

        panelPrefeito.setBackground(new java.awt.Color(255, 255, 255));
        panelPrefeito.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        lblSepPrefeito.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSepPrefeito.setForeground(new java.awt.Color(0, 0, 0));
        lblSepPrefeito.setText("Prefeito");

        javax.swing.GroupLayout panelPrefeitoLayout = new javax.swing.GroupLayout(panelPrefeito);
        panelPrefeito.setLayout(panelPrefeitoLayout);
        panelPrefeitoLayout.setHorizontalGroup(
            panelPrefeitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrefeitoLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblSepPrefeito)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        panelPrefeitoLayout.setVerticalGroup(
            panelPrefeitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrefeitoLayout.createSequentialGroup()
                .addComponent(lblSepPrefeito)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(panelPrefeito, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 190, 30));

        lblFotoVice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/images/fotoEdileneSantos.jpg"))); // NOI18N
        getContentPane().add(lblFotoVice, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, 160));

        panelVice.setBackground(new java.awt.Color(255, 255, 255));
        panelVice.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        lblSepVice.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblSepVice.setForeground(new java.awt.Color(0, 0, 0));
        lblSepVice.setText("Vice-Prefeito");

        javax.swing.GroupLayout panelViceLayout = new javax.swing.GroupLayout(panelVice);
        panelVice.setLayout(panelViceLayout);
        panelViceLayout.setHorizontalGroup(
            panelViceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViceLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblSepVice)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelViceLayout.setVerticalGroup(
            panelViceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViceLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblSepVice))
        );

        getContentPane().add(panelVice, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 160, 30));

        lblPrefeito.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblPrefeito.setForeground(new java.awt.Color(0, 0, 0));
        lblPrefeito.setText("PREFEITO(A)");
        getContentPane().add(lblPrefeito, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 200, -1));

        lblViceCandidato.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblViceCandidato.setForeground(new java.awt.Color(0, 0, 0));
        lblViceCandidato.setText("Vice:");
        getContentPane().add(lblViceCandidato, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        lblPartidoCandidato.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblPartidoCandidato.setForeground(new java.awt.Color(0, 0, 0));
        lblPartidoCandidato.setText("Partido:");
        getContentPane().add(lblPartidoCandidato, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        lblNumeroCandidato.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblNumeroCandidato.setForeground(new java.awt.Color(0, 0, 0));
        lblNumeroCandidato.setText("Número:");
        getContentPane().add(lblNumeroCandidato, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        lblNomeCandidato.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblNomeCandidato.setForeground(new java.awt.Color(0, 0, 0));
        lblNomeCandidato.setText("Nome:");
        getContentPane().add(lblNomeCandidato, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        panelNum2.setBackground(new java.awt.Color(255, 255, 255));
        panelNum2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        lblNum2.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        lblNum2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelNum2Layout = new javax.swing.GroupLayout(panelNum2);
        panelNum2.setLayout(panelNum2Layout);
        panelNum2Layout.setHorizontalGroup(
            panelNum2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNum2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNum2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelNum2Layout.setVerticalGroup(
            panelNum2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNum2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 60, 80));

        panelNum1.setBackground(new java.awt.Color(255, 255, 255));
        panelNum1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        lblNum1.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        lblNum1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelNum1Layout = new javax.swing.GroupLayout(panelNum1);
        panelNum1.setLayout(panelNum1Layout);
        panelNum1Layout.setHorizontalGroup(
            panelNum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNum1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNum1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelNum1Layout.setVerticalGroup(
            panelNum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNum1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNum1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(76, 76, 76))
        );

        getContentPane().add(panelNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 60, 80));

        lblConfirma.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblConfirma.setForeground(new java.awt.Color(0, 0, 0));
        lblConfirma.setText("VERDE para confirmar este voto ");
        getContentPane().add(lblConfirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        lblCorrige.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCorrige.setForeground(new java.awt.Color(0, 0, 0));
        lblCorrige.setText("VERMELHO para REINICIAR este voto");
        getContentPane().add(lblCorrige, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, 40));

        panelSeparador.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(panelSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 434, 520, 4));

        btn1.setContentAreaFilled(false);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 70, 50));

        btn2.setContentAreaFilled(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 70, 50));

        btn3.setContentAreaFilled(false);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, 70, 50));

        btn4.setContentAreaFilled(false);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 70, 60));

        btn5.setContentAreaFilled(false);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, 70, 60));

        btn6.setContentAreaFilled(false);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 220, 70, 60));

        btn7.setContentAreaFilled(false);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 70, 50));

        btn8.setContentAreaFilled(false);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, 70, 50));

        btn9.setContentAreaFilled(false);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 300, 70, 50));

        btn0.setContentAreaFilled(false);
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, -1, 50));

        btnBranco.setContentAreaFilled(false);
        btnBranco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrancoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBranco, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, 100, 50));

        btnConfirma.setContentAreaFilled(false);
        btnConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmaActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, 100, 70));

        btnCorrige.setContentAreaFilled(false);
        btnCorrige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorrigeActionPerformed(evt);
            }
        });
        getContentPane().add(btnCorrige, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 90, 50));

        figmaUrna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/images/urnaPoo.jpg"))); // NOI18N
        getContentPane().add(figmaUrna, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnBrancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBrancoActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmaActionPerformed

    private void btnCorrigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorrigeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCorrigeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUrna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBranco;
    private javax.swing.JButton btnConfirma;
    private javax.swing.JButton btnCorrige;
    private javax.swing.JLabel figmaUrna;
    private javax.swing.JLabel lblConfirma;
    private javax.swing.JLabel lblCorrige;
    private javax.swing.JLabel lblFotoPrefeito;
    private javax.swing.JLabel lblFotoVice;
    private javax.swing.JLabel lblNomeCandidato;
    private javax.swing.JLabel lblNum1;
    private javax.swing.JLabel lblNum2;
    private javax.swing.JLabel lblNumeroCandidato;
    private javax.swing.JLabel lblPartidoCandidato;
    private javax.swing.JLabel lblPrefeito;
    private javax.swing.JLabel lblSepPrefeito;
    private javax.swing.JLabel lblSepVice;
    private javax.swing.JLabel lblViceCandidato;
    private javax.swing.JPanel panelNum1;
    private javax.swing.JPanel panelNum2;
    private javax.swing.JPanel panelPrefeito;
    private javax.swing.JPanel panelSeparador;
    private javax.swing.JPanel panelVice;
    // End of variables declaration//GEN-END:variables
}
